import json
from app.agents.base import BaseAgent
from app.models.schedule import Schedule, ScheduleItem
from app.models.fresher import Fresher
from app.models.curriculum import Curriculum


class OnboardingAgent(BaseAgent):
    """The Architect — generates personalized daily schedules for trainees."""

    def __init__(self):
        super().__init__(model_name=None)  # uses default model

    def execute(self, db, fresher: Fresher, target_date: str):
        # 1. Get curriculum
        curriculum = db.query(Curriculum).first()
        curriculum_info = curriculum.name if curriculum else "General Software Engineering"

        # 2. Get user info
        from app.models.user import User
        user = db.query(User).filter(User.id == fresher.user_id).first()
        user_name = f"{user.first_name} {user.last_name}" if user else "Trainee"

        # 3. Check existing schedule
        existing = db.query(Schedule).filter(
            Schedule.fresher_id == fresher.id,
            Schedule.schedule_date == target_date,
        ).first()
        if existing:
            items = db.query(ScheduleItem).filter(ScheduleItem.schedule_id == existing.id).all()
            return {
                "schedule_id": str(existing.id),
                "date": target_date,
                "status": "already_exists",
                "items_count": len(items),
            }

        # 4. Generate schedule with LLM
        prompt = f"""
Generate a personalized daily training schedule for {user_name}.
Current week: {fresher.current_week}
Progress: {fresher.overall_progress}%
Curriculum: {curriculum_info}
Date: {target_date}

Output a JSON object with a "tasks" array. Each task should have:
- time (HH:MM format)
- title (string)
- type (one of: reading, video, coding, quiz, project, assessment)
- duration (minutes as integer)
"""
        response = self.call_llm(prompt, system="You are an AI training schedule planner.")

        # 5. Parse LLM response
        try:
            data = json.loads(response)
            tasks = data.get("tasks", [])
        except Exception:
            tasks = [
                {"time": "09:00", "title": "Python Fundamentals", "type": "reading", "duration": 60},
                {"time": "10:00", "title": "Coding Practice", "type": "coding", "duration": 45},
                {"time": "11:00", "title": "Quiz: Basics", "type": "quiz", "duration": 30},
                {"time": "13:00", "title": "Data Structures", "type": "video", "duration": 60},
                {"time": "14:00", "title": "Coding Challenge", "type": "coding", "duration": 60},
                {"time": "15:00", "title": "Mini Project", "type": "project", "duration": 90},
            ]

        # 6. Store schedule
        schedule = Schedule(
            fresher_id=fresher.id,
            schedule_date=target_date,
            status="pending",
        )
        db.add(schedule)
        db.commit()
        db.refresh(schedule)

        for task in tasks:
            item = ScheduleItem(
                schedule_id=schedule.id,
                title=task.get("title", "Training Task"),
                description=f"Auto-generated by Onboarding Agent for Week {fresher.current_week}",
                item_type=task.get("type", "reading"),
                duration_minutes=task.get("duration", 30),
                status="pending",
                topic=task.get("title", ""),
                start_time=task.get("time", "09:00"),
            )
            db.add(item)

        db.commit()

        return {
            "schedule_id": str(schedule.id),
            "date": target_date,
            "status": "generated",
            "items_count": len(tasks),
            "agent": "OnboardingAgent",
        }
